---
  - hosts: "vagrant"
    gather_facts: True 
    sudo: True
    vars:
      ack_mode: on-publish
      prefetch_count: 1000
    tasks:
      - name: set up federation from all satellite nodes to master
        command: >
          rabbitmqctl set_parameter federation-upstream {{item}}
          '{
          "uri":"amqp://rabbit:rabbit@{{hostvars[item]['ansible_eth1']['ipv4']['address']}}",
          "trust-user-id":true,
          "max-hops": 1,
          "prefetch-count": {{ prefetch_count }}
          }'
        with_items: "groups.vagrant[1:]"
        when: 'inventory_hostname == groups.vagrant[0]'

      - name: set up an upstream-set from master to satellites (for inbound metrics)
        command: >
            rabbitmqctl set_parameter federation-upstream-set sats 
            '[{% for i in groups.vagrant[1:] %}{"upstream":"{{ i }}"}{% if not loop.last %},{% endif %}{%endfor%}]'
        when: 'inventory_hostname == groups.vagrant[0]'

      - name: set up rabbitmq federation policy for messages exchange
        command: >
          rabbitmqctl set_policy federate-messages "^fed-exchange-hash-exchange$" 
          '{"federation-upstream-set":"sats"}'
        when: 'inventory_hostname == groups.vagrant[0]'

      - name: create fed-exchange-hash-exchange exchanges on all hosts
        command: >
          rabbitmqadmin declare exchange
          name="fed-exchange-hash-exchange"
          type="topic"
          auto_delete=false
          internal=false
          durable=true

      - name: create hashing exchange on master
        command: >
          rabbitmqadmin declare exchange
          name="fed-exchange-hash-exchange-hashing"
          type="x-consistent-hash"
          auto_delete=false
          internal=false
          durable=true
        when: 'inventory_hostname == groups.vagrant[0]'

      - name: create fed-exchange-hash-exchange -> fed-exchange-hash-exchange-hashing binding
        command: > 
          rabbitmqadmin declare binding
          source="fed-exchange-hash-exchange" 
          destination_type="exchange" 
          destination="fed-exchange-hash-exchange-hashing"
          routing_key="10"
        when: 'inventory_hostname == groups.vagrant[0]'
